<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    //
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=["id","type"]
    protected $table = "categories";
    protected $fillable=[];
}